//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NombreMagique.Component
{
    public partial class Game
    {
        private const int life = 5;
        private const int Min = 1;
        private const int Max = 20;

        private int nbMagic; // donne le nbre aléatoire 
        private bool? gameWon; // indique si on gagne ou on perd, oubien le jeu en cour
        private int nbRemainingLifes;
        private int? value;
        private string indice; // qui indique si le nombre est plus grand ou pétit

        protected override void OnInitialized()
        {
            initGame();
        }
        private void initGame()
        {
            gameWon = null;
            nbMagic = Random.Shared.Next(Min, Max + 1);
            nbRemainingLifes = life;
            value = null;
            indice = null;
        }

        private void CheckNumber()
        {
            if (value == nbMagic)
            {
                gameWon = true;
                indice = null;
                return;
            }
            nbRemainingLifes--;
            if (nbRemainingLifes <= 0)
            {
                gameWon = false;
                indice = null;
                return;
            }
            if (value > nbMagic) indice = "Le nombre de magique est plus pétit";
            else if (value < nbMagic) indice = "le nombre de magique est plus grand";
        }
    }
}