// <auto-generated/>
using InitBlazor.Models;

namespace InitBlazor.Composant
{
    public partial class Weather
    {
        private WeatherForecast[]? forecasts;

        protected override async Task OnInitializedAsync()
        {
            // Simulate asynchronous loading to demonstrate a loading indicator
            await Task.Delay(500);

            forecasts = await forecastSevice.GetWeatherForecastAsync();
        }

    }
}