// <auto-generated/>
using NbreMagique.Model;

namespace NbreMagiqueBlazor.Component
{
    public partial class Weather
    {
        private WeatherForecast[]? forecasts;

        protected override async Task OnInitializedAsync()
        {

            forecasts = await ForecastService.GetWeatherForecastsAsync();
        }


    }
}